
# LD2410C Presence Sensor
ld2410:
  id: ld2410_radar
uart:
  tx_pin: ${pin_ld2410_ptx}
  rx_pin: ${pin_ld2410_prx}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 2048

switch:
  - platform: ld2410
    engineering_mode:
      name: "ld2410 Engineering mode"
      entity_category: "DIAGNOSTIC"
    bluetooth:
      name: "ld2410 bluetooth control"
      entity_category: "CONFIG"

button:
  - platform: ld2410
    restart:
      name: "ld2410 restart"
      entity_category: "DIAGNOSTIC"
    factory_reset:
      name: "ld2410 factory reset"
      entity_category: "DIAGNOSTIC"
      disabled_by_default: True
    query_params:
      name: "ld2410 query params"
      entity_category: "DIAGNOSTIC"
      disabled_by_default: True

select:
  - platform: ld2410
    distance_resolution:
      name: "ld2410 Distance resolution"
      entity_category: "CONFIG"
      disabled_by_default: True
    baud_rate:
      name: "ld2410 Baud rate"
      entity_category: "CONFIG"
      disabled_by_default: True
    light_function:
      name: "ld2410 Light function"
      entity_category: "CONFIG"
      disabled_by_default: True
    out_pin_level:
      name: Out pin level
      entity_category: "CONFIG"
      disabled_by_default: True

sensor:
  # Presence sensors
  - platform: ld2410
    moving_distance:
      name: Moving Distance
      id: moving_distance
      entity_category: "DIAGNOSTIC"
      filters:
        - delta: 10.0
        - throttle: 5s
    still_distance:
      name: Still Distance
      id: still_distance
      entity_category: "DIAGNOSTIC"
      filters:
        - delta: 10.0
        - throttle: 5s
    detection_distance:
      name: Detection Distance
      id: radar_detection_distance
      entity_category: "DIAGNOSTIC"
    moving_energy:
      name: Moving Energy
      id: moving_energy
      entity_category: "DIAGNOSTIC"
    still_energy:
      name: Still Energy
      id: still_energy
      entity_category: "DIAGNOSTIC"

binary_sensor:
  # Presence binary sensors
  - platform: ld2410
    has_target:
      name: Presence
      id: ld2410_presence
      filters:
        - delayed_on: 1s
        - delayed_off: 1s
        - settle: 1000ms
      on_press:
        - script.execute: 
            id: update_presence
            trigger: 0
      on_release:
        - script.execute: 
            id: update_presence
            trigger: 0
    has_moving_target:
      name: Motion
      id: ld2410_moving_target
      filters:
        - delayed_on: 1s
        - delayed_off: 4s
        - settle: 1000ms
      on_press:
        - script.execute: 
            id: update_presence
            trigger: 1
      on_release:
        - script.execute: 
            id: update_presence
            trigger: 1
    

text_sensor:
  - platform: ld2410
    version:
      name: "ld2410 Firmware version"
      entity_category: "DIAGNOSTIC"
    mac_address:
      name: MAC address
      entity_category: "DIAGNOSTIC"

number:
  - platform: ld2410
    timeout:
      name: Timeout
    light_threshold:
      name: Light threshold
      entity_category: "CONFIG"
    max_move_distance_gate:
      name: Max move distance gate
      entity_category: "CONFIG"
      disabled_by_default: True
    max_still_distance_gate:
      name: Max still distance gate
      entity_category: "CONFIG"
      disabled_by_default: True
    g0:
      move_threshold:
        name: G0 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G0 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g1:
      move_threshold:
        name: G1 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G1 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g2:
      move_threshold:
        name: G2 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G2 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g3:
      move_threshold:
        name: G3 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G3 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g4:
      move_threshold:
        name: G4 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G4 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g5:
      move_threshold:
        name: G5 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G5 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g6:
      move_threshold:
        name: G6 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G6 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g7:
      move_threshold:
        name: G7 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G7 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True
    g8:
      move_threshold:
        name: G8 move threshold
        entity_category: "CONFIG"
        disabled_by_default: True
      still_threshold:
        name: G8 still threshold
        entity_category: "CONFIG"
        disabled_by_default: True

script:
  - id: update_presence
    parameters:
      # 0=presence, 1=motion
      trigger: int
    then:
      - if:
          condition:
            lambda: 'return trigger == 0;'
          then:
            - if:
                condition:
                  binary_sensor.is_on: ld2410_presence
                then:
                  # Presence detected
                  - logger.log:
                      format: "Presence Detected"
                      level: INFO
                else:
                  # Presence cleared
                  - logger.log:
                      format: "Presence Cleared"
                      level: INFO
      - if:
          condition:
            lambda: 'return trigger == 1;'
          then:
            - if:
                condition:
                  binary_sensor.is_on: ld2410_moving_target
                then:
                  # Motion detected
                  - logger.log:
                      format: "Motion Detected"
                      level: INFO
                else:
                  # Motion cleared
                  - logger.log:
                      format: "Motion Cleared"
                      level: INFO

