web_server:
  id: the_web_server
  port: 8080
  ota: False
  log: True
  local: True
  version: 3

button:
  - platform: restart
    id: restart_button
    name: Restart
    entity_category: "DIAGNOSTIC"

sensor:
  - platform: uptime
    id: uptime_sensor
    name: Uptime
    entity_category: "DIAGNOSTIC"
    unit_of_measurement: s
    update_interval: 10s
  - platform: internal_temperature
    id: cpu_temperature_sensor
    name: "CPU Temperature"
    entity_category: "DIAGNOSTIC"

text_sensor:
  - platform: wifi_info
    ip_address:
      id: esp_wifi_address
      name: ESP IP Address
      entity_category: "DIAGNOSTIC"
      disabled_by_default: True
    ssid:
      id: esp_wifi_ssid
      name: ESP Connected SSID
      entity_category: "DIAGNOSTIC"
      disabled_by_default: True
