substitutions:
  device_name: "front-entry-sensor"
  friendly_devicename: "Front Entry Sensor"
  outdoor_sensor_mac_address: !secret mac_outdoor_sensor
  indoor_sensor_mac_address: !secret mac_indoor_sensor
  pin_led: GPIO16
  # mmwave sensor uart pins
  pin_prx: GPIO18
  pin_ptx: GPIO19
  # the timezone for ntp_time
  timezone: !secret timezone

esphome:
  name: ${device_name}
  friendly_name: ${friendly_devicename}
  area: Front Entry

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: recommended

logger:
  level: INFO
  baud_rate: 0

api:
  encryption:
    key: !secret encryption_key
  # on_client_connected:
  #   - logger.log:
  #       format: "API: Starting BLE scanning"
  #       level: INFO
  #   - esp32_ble_tracker.start_scan:
  #       continuous: True
  # on_client_disconnected:
  #   - esp32_ble_tracker.stop_scan:
  #   - logger.log:
  #       format: "API: Stopping BLE scanning"
  #       level: INFO

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  id: the_web_server
  port: 8080
  ota: False
  log: True
  local: True
  version: 3

bluetooth_proxy:
  active: True
  connection_slots: 4

esp32_ble:
  max_connections: 4

esp32_ble_tracker:
  scan_parameters:
    continuous: True
    active: True

time:
  - platform: sntp
    id: ntp_time
    timezone: ${timezone}
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
    on_time:
      # Every 10 minutes
      - seconds: 0
        minutes: /10
        then:
          - logger.log:
              format: "Starting timed BLE scan"
              level: INFO
          - esp32_ble_tracker.start_scan:
              continuous: True
    on_time_sync:
      then:
        - logger.log:
            format: "Time Synchronized over ntp"
            level: INFO
            
# LD2410C Presence Sensor
ld2410:
  id: ld2410_radar
uart:
  tx_pin: ${pin_ptx}
  rx_pin: ${pin_prx}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 2048
  
switch:
  - platform: ld2410
    engineering_mode:
      name: "ld2410 Engineering mode"
      entity_category: "DIAGNOSTIC"
    bluetooth:
      name: "ld2410 bluetooth control"
  - platform: template
    id: led_active_mode_select
    name: "LED Enable"
    icon: "mdi:led-outline"
    entity_category: "CONFIG"
    optimistic: True
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - logger.log:
            format: "Enabling status LED"
            level: INFO
      - script.execute: update_status_led
    on_turn_off:
      - logger.log:
            format: "Disabling status LED"
            level: INFO
      - script.execute: update_status_led
        
button:
  - platform: restart
    id: restart_button
    name: Restart
    entity_category: "DIAGNOSTIC"
  - platform: ld2410
    factory_reset:
      name: "ld2410 factory reset"
      entity_category: "DIAGNOSTIC"
    restart:
      name: "ld2410 restart"
      entity_category: "DIAGNOSTIC"
    query_params:
      name: "ld2410 query params"
      entity_category: "DIAGNOSTIC"
      
sensor:
  - platform: uptime
    id: uptime_sensor
    name: Uptime
    entity_category: "DIAGNOSTIC"
    unit_of_measurement: s
    update_interval: 10s
    
  # Presence sensors
  - platform: ld2410
    moving_distance:
      name: Moving Distance
      id: moving_distance
      entity_category: "DIAGNOSTIC"
      filters:
        - delta: 10.0
        - throttle: 5s
    still_distance:
      name: Still Distance
      id: still_distance
      entity_category: "DIAGNOSTIC"
      filters:
        - delta: 10.0
        - throttle: 5s
    detection_distance:
      name: Detection Distance
      id: radar_detection_distance
      entity_category: "DIAGNOSTIC"
    moving_energy:
      name: Moving Energy
      id: moving_energy
      entity_category: "DIAGNOSTIC"
    still_energy:
      name: Still Energy
      id: still_energy
      entity_category: "DIAGNOSTIC"

binary_sensor:
  # Presence binary sensors
  - platform: ld2410
    has_target:
      name: Presence
      id: ld2410_presence
      filters:
        - delayed_on: 1s
        - delayed_off: 1s
        - settle: 1000ms
      on_press:
        - script.execute: update_status_led
      on_release:
        - script.execute: update_status_led
    has_moving_target:
      name: Motion
      id: ld2410_moving_target
      filters:
        - delayed_on: 1s
        - delayed_off: 4s
        - settle: 1000ms
      on_press:
        - script.execute: update_status_led
      on_release:
        - script.execute: update_status_led
    has_still_target:
      name: Still Target
      id: ld2410_still_target
      on_press:
        - script.execute: update_status_led
      on_release:
        - script.execute: update_status_led

text_sensor:
  - platform: ld2410
    version:
      name: "ld2410 Firmware version"
      entity_category: "DIAGNOSTIC"
    mac_address:
      name: MAC address
      entity_category: "DIAGNOSTIC"

select:
  - platform: ld2410
    distance_resolution:
      name: "ld2410 Distance resolution"
    baud_rate:
      name: "ld2410 Baud rate"
    light_function:
      name: "ld2410 Light function"
    out_pin_level:
      name: Out pin level

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    rgb_order: GRB
    pin: ${pin_led}
    num_leds: 1
    chipset: ws2812

number:
  - platform: ld2410
    timeout:
      name: Timeout
    light_threshold:
      name: Light threshold
    max_move_distance_gate:
      name: Max move distance gate
    max_still_distance_gate:
      name: Max still distance gate
    g0:
      move_threshold:
        name: G0 move threshold
        disabled_by_default: True
      still_threshold:
        name: G0 still threshold
        disabled_by_default: True
    g1:
      move_threshold:
        name: G1 move threshold
        disabled_by_default: True
      still_threshold:
        name: G1 still threshold
        disabled_by_default: True
    g2:
      move_threshold:
        name: G2 move threshold
        disabled_by_default: True
      still_threshold:
        name: G2 still threshold
        disabled_by_default: True
    g3:
      move_threshold:
        name: G3 move threshold
        disabled_by_default: True
      still_threshold:
        name: G3 still threshold
        disabled_by_default: True
    g4:
      move_threshold:
        name: G4 move threshold
        disabled_by_default: True
      still_threshold:
        name: G4 still threshold
        disabled_by_default: True
    g5:
      move_threshold:
        name: G5 move threshold
        disabled_by_default: True
      still_threshold:
        name: G5 still threshold
        disabled_by_default: True
    g6:
      move_threshold:
        name: G6 move threshold
        disabled_by_default: True
      still_threshold:
        name: G6 still threshold
        disabled_by_default: True
    g7:
      move_threshold:
        name: G7 move threshold
        disabled_by_default: True
      still_threshold:
        name: G7 still threshold
        disabled_by_default: True
    g8:
      move_threshold:
        name: G8 move threshold
        disabled_by_default: True
      still_threshold:
        name: G8 still threshold
        disabled_by_default: True
  # Presence LED settings
  - platform: template
    name: "LED Presence Brightness"
    id: presence_brightness
    icon: "mdi:brightness-percent"
    entity_category: "CONFIG"
    optimistic: true
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 50
    unit_of_measurement: "%"
    restore_value: true
    on_value:
      - script.execute: update_status_led

  # Motion LED settings
  - platform: template
    name: "LED Motion Brightness"
    id: motion_brightness
    icon: "mdi:brightness-percent"
    entity_category: "CONFIG"
    optimistic: true
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 50
    unit_of_measurement: "%"
    restore_value: true
    on_value:
      - script.execute: update_status_led
    
script:
  - id: update_status_led
    then:
      - if:
          condition:
            switch.is_on: led_active_mode_select
          then:
            - if:
                condition:
                  binary_sensor.is_on: ld2410_moving_target
                then:
                  # Motion detected - RED
                  - logger.log:
                      format: "Motion Detected"
                      level: INFO
                  - light.turn_on:
                      id: status_led
                      red: 100%
                      green: 0%
                      blue: 0%
                      brightness: !lambda 'return id(motion_brightness).state / 100.0;'
                else:
                  - if:
                      condition:
                        binary_sensor.is_on: ld2410_presence
                      then:
                        # Presence only - BLUE
                        - logger.log:
                            format: "Presence Detected"
                            level: DEBUG
                        - light.turn_on:
                            id: status_led
                            red: 0%
                            green: 0%
                            blue: 100%
                            brightness: !lambda 'return id(presence_brightness).state / 100.0;'
                      else:
                        # No presence - OFF
                        - light.turn_off:
                            id: status_led
          else:
            # Status LED disabled
            - logger.log:
                format: "Presence Cleared"
                level: INFO
            - light.turn_off:
                id: status_led