substitutions:
  devicename: "garage-sensor"
  friendly_devicename: "Garage Sensor"
  pin_door_1: GPIO32
  pin_door_2: GPIO33
  # status light
  pin_status: GPIO2
  # mmwave sensor uart pins
  pin_prx: GPIO16
  pin_ptx: GPIO17
  # light sensor
  pin_light_sensor: GPIO34
  light_threshold: "2.7"
  # i2c Display pins
  pin_sda: GPIO21
  pin_scl: GPIO22
  motion_off_delay: 8s

packages: 
  bz0qyz.shelly2pm-base:
    url: https://github.com/bz0qyz/esphome
    files:
      - common/diagnostic-entities.yaml
    ref: main
    refresh: 30min

esphome:
  name: ${devicename}
  friendly_name: ${friendly_devicename}
  area: Garage

esp32:
  board: esp32dev
  framework:
    # type: esp-idf
    type: arduino
    version: recommended

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret hostpot_password

captive_portal:


time:
  - platform: homeassistant

udp:
  - id: udp_output
    addresses:
      - 192.168.4.80

packet_transport:
  - platform: udp
    id: transport_output
    udp_id: udp_output
    update_interval: 1s
    encryption: !secret udp_encryption
    rolling_code_enable: true
    binary_sensors:
      - presence
      - moving_target
      - gpio_garage_door_1
      - gpio_garage_door_2

# i2c Display
i2c:
  - id: bus_a
    sda: ${pin_sda}
    scl: ${pin_scl}
    frequency: 400kHz
display:
  - platform: lcd_pcf8574
    id: display1
    dimensions: 16x2
    address: 0x27
    i2c_id: bus_a
    update_interval: 1000ms
    user_characters:
      - position: 1
        data:
          - 0b00000
          - 0b01110
          - 0b01110
          - 0b01110
          - 0b00100
          - 0b11111
          - 0b11111
          - 0b11111
      - position: 2
        data:
          - 0b10101
          - 0b01010
          - 0b00101
          - 0b00010
          - 0b01101
          - 0b01100
          - 0b11110
          - 0b11110
    lambda: |-
      // print door prefixes
      it.print(0, 0, "DOOR1: ");
      it.print(0, 1, "DOOR2: ");
      // set the door 1 status
      if (id(gpio_garage_door_1).state) {
        it.printf(7, 0, "OPEN");
      } else {
        it.printf(7, 0, "CLOSED");
      }
      // set the door 2 status
      if (id(gpio_garage_door_2).state) {
        it.printf(7, 1, "OPEN");
      } else {
        it.printf(7, 1, "CLOSED");
      }
      // set the presence status
      if (id(presence).state) {
        it.print(15, 1, "\x01");
      } else {
        it.print(15, 1, " ");
      }
      // set the motion status
      if (id(moving_target).state) {
        it.print(15, 0, "\x02");
      } else {
        it.print(15, 0, " ");
      }
      

# LD2410C Presence Sensor
ld2410:
  id: ld2410_radar
uart:
  tx_pin: ${pin_ptx}
  rx_pin: ${pin_prx}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

light:
  - platform: status_led
    id: status_light
    name: "Status Light"
    pin: ${pin_status}


sensor:
  # Presence sensor binary sensors
  # - platform: ld2410
  #   moving_distance:
  #     name: Moving Distance
  #     id: moving_distance
  #     entity_category: "DIAGNOSTIC"
  #   still_distance:
  #     name: Still Distance
  #     id: still_distance
  #     entity_category: "DIAGNOSTIC"
  #   detection_distance:
  #     name: Detection Distance
  #     id: radar_detection_distance
  #     entity_category: "DIAGNOSTIC"

  - platform: internal_temperature
    id: "esp32_cpu_temp"
    name: "Internal Temperature"
    entity_category: "DIAGNOSTIC"

  - platform: wifi_signal
    id: "esp32_wiFi_signal"
    name: "WiFi Signal"
    update_interval: 30s
    disabled_by_default: true

binary_sensor:
  # Presence sensor binary sensors
  - platform: ld2410
    has_target:
      name: Presence
      id: presence
      filters:
        - delayed_on: 1s
        - delayed_off: 1s
      # Start the auto-off light timer script if no presence is detected  
      on_press:
        - switch.turn_on: display_backlight_switch
      on_release: 
        then:
        - switch.turn_off: display_backlight_switch
      
    has_moving_target:
      name: Motion
      id: moving_target
      filters:
        - delayed_on: 0s
        - delayed_off: ${motion_off_delay}
      on_state:
        then:
          - if:
              condition:
                - lambda: 'return id(moving_target).state;'
              then:
                - light.turn_on:
                    id: status_light
              else:
                - light.turn_off:
                    id: status_light
          - if:
              condition:
                - lambda: |-
                    if (id(display_backlight_mode).current_option() == "Motion") {
                        return true;
                    } else {
                        return false;
                    }
              then:
                - if:
                    condition:
                      - lambda: 'return id(moving_target).state;'
                    then:
                      - switch.turn_on: display_backlight_switch
                    else:
                      - switch.turn_off: display_backlight_switch
    has_still_target:
      name: Still Target
      id: still_target
    out_pin_presence_status:
      name: out pin presence status
      filters:
        - delayed_on: 1s
        - delayed_off: 1s


  - platform: status
    id: "esp32_status"
    name: "Status"

  # Garage Door 1
  - platform: gpio
    filters:
      - delayed_off: 20ms
      - settle: 0.5s
    pin:
      number: ${pin_door_1}
      mode: INPUT_PULLDOWN
      inverted: True
      allow_other_uses: false
    name: "Garage Door 1"
    id: "gpio_garage_door_1"
    device_class: garage_door
    on_press:
      - logger.log: "Garage Door 1 Opened"
    on_release:
       - logger.log: "Garage Door 1 Closed"

  # Garage Door 2  
  - platform: gpio
    filters:
      - delayed_off: 20ms
      - settle: 0.5s
    pin:
      number: ${pin_door_2}
      mode: INPUT_PULLDOWN
      inverted: True
      allow_other_uses: false
    name: "Garage Door 2"
    id: "gpio_garage_door_2"
    device_class: garage_door
    on_press:
      - logger.log: "Garage Door 2 Opened"
    on_release:
       - logger.log: "Garage Door 2 Closed"

  - platform: gpio
    name: "Garage Light Sensor"
    id: "garage_light_sensor"
    icon: mdi:lightbulb
    pin:
      number: ${pin_light_sensor}
      inverted: True
    filters:
      settle: 100ms
  
select:
  - platform: template
    id: display_backlight_mode
    name: "Backlight Mode"
    icon: "mdi:auto-mode"
    optimistic: true
    options:
      - "Motion"
      - "Presence"
      - "Manual"
    initial_option: "Motion"
    restore_value: true
    
switch:
  - platform: template
    id: display_backlight_switch
    name: "Manual Backlight"
    icon: "mdi:lightbulb-on"
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - lambda: id(display1).backlight();
      - switch.template.publish:
          id: display_backlight_switch
          state: ON
    turn_off_action:
      - lambda: id(display1).no_backlight();
      - switch.template.publish:
          id: display_backlight_switch
          state: OFF
