substitutions:
  devicename: "patio-lights"
  friendly_devicename: "Patio Lights"
  # relay switch gpio
  output_name: "Patio Lights"
  output_icon: "mdi:string-lights"
  outout_gpio: GPIO26

packages: 
  bz0qyz.shelly2pm-base:
    url: https://github.com/bz0qyz/esphome
    files:
      - common/diagnostic-entities.yaml
    ref: main
    refresh: 30min

esphome:
  name: ${devicename}
  friendly_name: ${friendly_devicename}
  area: Patio

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
# Enable Home Assistant API
api:
  encryption:
    key: !secret patio_encryption_key

ota:
  - platform: esphome
    password: !secret patio_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Hotspot"
    password: !secret hostpot_password

captive_portal:


switch:
  - platform: gpio
    id: relay
    name: Light Switch
    internal: true
    pin:
      number: ${outout_gpio}
      inverted: false
    on_turn_on:
      - light.turn_on: light_1
      - light.turn_on: relay_led
    on_turn_off:
      - light.turn_off: light_1
      - light.turn_off: relay_led

output:
  - platform: gpio
    pin: GPIO19
    inverted: True
    id: relay1_led_gpio

light:
  - platform: binary
    id: light_1
    name: "${output_name}"
    output: relay1_led_gpio
    icon: "${output_icon}"
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on: 
      - switch.turn_on: relay
    on_turn_off: 
      - switch.turn_off: relay

  - platform: binary
    name: "Relay LED"
    id: relay_led
    internal: true
    output: relay1_led_gpio

binary_sensor:
  - platform: status
    id: "esp32_status"
    name: "Status"
  - platform: gpio
    internal: true
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: false
    name: Switch
    on_state:
      - switch.toggle: relay
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: false
    name: Button
    on_press:
      - switch.toggle: relay
